config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tasks
  resources :articles
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  get 'users/new'
  get 'users/create'
  get 'tasks/new'
  get '/privacy' => 'pages#privacy'
  get '/progress' => 'pages#progress'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'sessions#welcome'
  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  # match '/privacy' => 'pages#privacy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized
    helper_method :logged_in?
    helper_method :current_user
    helper_method :all_articles
    
    
    def all_articles  
        Article.all
    end
    
    def current_user   
        User.find_by(id: session[:user_id])
    end

    def logged_in?
        # byebug
        !current_user.nil?  
    end

    def authorized
        redirect_to '/' unless logged_in?
     end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :text, :image, :text_on_left)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def privacy
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorized, only: [:new, :create, :welcome]
  
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
        session[:user_id] = user.id 
        redirect_to '/'
    else
      flash.now[:alert] = "Incorrect email or password."
      render :new, status: :bad_request
    end
  end

  def destroy
    session[:user_id] = ''
    redirect_to '/'
  end

  def welcome
    
  end

  def login
  end

  def page_requires_login
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authorized, only: [:new, :create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:username, :password))
    session[:user_id] = @user.id
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= article.text %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= article.image %>
  </p>

  <p>
    <strong>Text on left:</strong>
    <%= article.text_on_left %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :text_on_left, style: "display: block" %>
    <%= form.check_box :text_on_left %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <p>@ Copyright 2022 Tasks Manager<p>
    <a href='/privacy'>Privacy policy</a>
</footer>

app/views/layouts/_header.html.erb
<header class="d-flex justify-content-between p-2 bg-light mb-4 sticky-top align-items-start">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                <%if logged_in?%>
                    <%= link_to "New task", new_task_path, :class => 'nav-item nav-link' %>
                    <a class="nav-item nav-link" href="/tasks">My tasks</a>
                    <a class="nav-item nav-link" href="/progress">Progress</a>
                    <%= button_to "Logout", '/logout', method: :get, :class => 'nav-item nav-link logout-button'%>
                <%end%>
                <%if !logged_in?%>
                    <a href="/login" class="nav-item nav-link">Login</a>
                    <a href="/users/new" class="nav-item nav-link">Register</a>
                <%end%>
            </div>
        </div>
    </nav>
    <%if logged_in?%>
        <p class="mb-0 pt-3 pr-3 d-flex align-items-center color-grey">Hello <%= current_user.username%></p>
    <%end%>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>TasksManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-vh-100 d-flex flex-column justify-content-between">
    <%= render "layouts/header" %>
    <main>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/privacy.html.erb
<div class="container">
    <h1 class="mb-3">Privacy Policy</h1>
    <h2>What is Lorem Ipsum?</h2>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

    <h2>Why do we use it?</h2>
    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>


    <h2>Where does it come from?</h2>
    <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>

    <p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
</div>

app/views/pages/progress.html.erb
<%
    toDoTasks = 0
    doneTasks = 0
    current_user.tasks.each do |task|
        if task.status == true
            doneTasks += 1
        else
           toDoTasks += 1
        end 
    end
    if current_user.tasks.length() > 0
        percentageDoneTasks = (doneTasks * 100) / current_user.tasks.length()
    else 
        percentageDoneTasks = 0
    end
%>

<div class="container">
    <h1 class="mb-4 small-header">Your progress in doing tasks</h1>
    <div class="progress mb-4 bg-secondary">
        <div
            class="progress-bar bg-warning"
            role="progressbar"
            style="width: <%= "#{percentageDoneTasks}"%>%"
            aria-valuenow="75"
            aria-valuemin="0"
            aria-valuemax="<%= "#{current_user.tasks.length()}"%>">
        </div>
    </div>
    <div>
        <div class="d-flex align-items-center mb-2">
            <div class="circle mr-2 bg-warning"></div>
            <p class="mb-0"><%= doneTasks%> done tasks</p>
        </div>
        <div class="d-flex align-items-center">
            <div class="circle mr-2 bg-secondary"></div>
            <p class="mb-0"><%= toDoTasks%> tasks to do</p>
        </div>
    </div>
<div>

app/views/tasks/_form.html.erb
<div class="container form-container">
  <%= form_with(model: task) do |form| %>
    <% if task.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
          <% task.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= render(FormInputComponent.new(id: "title-input")) do %>
      <%=
        form.text_field :title,
        placeholder: "Title",
        :'aria-label' => "Title",
        :class => 'form-control my-form-control',
        required: true
      %>
    <% end %>

    <%= render(FormInputComponent.new(id: "description-input")) do %>
      <%=
        form.text_area :description,
        placeholder: "Description",
        :'aria-label' => "Description",
        :class => 'form-control my-form-control'
      %>
    <% end %>

    <%= render(FormInputComponent.new(id: "status-input")) do %>
      <%= form.label :status, :class => 'mr-1 mb-0' %>
      <%= form.check_box :status %>
    <% end %>

    <div>
      <%= form.submit :class => 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1 class="header">Editing task</h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  <h1 class="mb-4">My tasks</h1>
  <div id="tasks" class="tasks-list">
    <div class="task-column">
      <h2 class="mb-3">To do</h2>
      <% current_user.tasks.each do |task| %>
        <% if task.status == false %>
          <%= render task %>
        <% end %>
      <% end %>
    </div>
    <div class="task-column">
      <h2 class="mb-3">Done</h2>
      <% current_user.tasks.each do |task| %>
        <% if task.status == true %>
          <%= render task %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<h1 class="header">New task</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<div class="container show-container">
  <p style="color: green"><%= notice %></p>
  <%= render @task %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1 class="header">Sign In</h1>

<div class="container form-container">

    <%= form_for @user do |f|%>
        <%= render(FormInputComponent.new(id: "description-username")) do %>
            <%=
                f.text_field :username,
                placeholder: "username",
                :'aria-label' => "username",
                :class => 'form-control my-form-control'
            %>
        <% end %>
        <%= render(FormInputComponent.new(id: "description-password")) do %>
            <%=
                f.password_field :password,
                placeholder: "password",
                :'aria-label' => "password",
                :class => 'form-control my-form-control'
            %>
        <% end %>
        <%= f.submit :class => 'btn btn-secondary' %>
    <%end%>
</div>